// scripts/generateMeals.mjs
// Node script to auto-generate a big meals DB (~1200 meals) with basic recipes.
// Run with:  node scripts/generateMeals.mjs

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// --- Types as strings for the generated TS file ---
const header = `// AUTO-GENERATED BY scripts/generateMeals.mjs
// Do not edit this file directly. Re-run the generator instead.

export type DietStyle =
  | "balanced"
  | "keto"
  | "high-protein"
  | "low-fodmap"
  | "mediterranean";

export type MealType = "breakfast" | "lunch" | "dinner" | "small-meal";

export type Ingredient = {
  name: string;
  unit?: string;
  quantity?: number;
};

export type Recipe = {
  ingredients: Ingredient[];
  steps: string[];
};

export type MealTemplate = {
  id: string;
  name: string;
  mealType: MealType;
  baseCalories: number;
  dietStyles: DietStyle[];
  flags: {
    ibsSafe: boolean;
    glutenFree: boolean;
    immuneSafe: boolean;
  };
  recipe: Recipe;
};

export const MEALS: MealTemplate[] = 
`;

// ---------- Generator logic ----------

// Helpers to pick from arrays
const choice = (arr, index) => arr[index % arr.length];

const dietStyles = [
  "balanced",
  "keto",
  "high-protein",
  "low-fodmap",
  "mediterranean",
];

const mealTypes = ["breakfast", "lunch", "dinner", "small-meal"];

const cuisines = [
  "Mediterranean",
  "Mexican",
  "Asian",
  "American",
  "Italian",
  "Middle Eastern",
  "Greek",
  "Japanese",
  "Thai",
  "Indian",
];

const proteins = [
  "Chicken breast",
  "Salmon fillet",
  "Firm tofu",
  "Ground turkey",
  "Eggs",
  "Lean beef",
  "Lentils",
  "Shrimp",
  "Tempeh",
  "Chickpeas",
];

const carbs = [
  "Quinoa",
  "Brown rice",
  "Sweet potato",
  "Cauliflower rice",
  "Rolled oats",
  "Mixed greens",
  "Zucchini noodles",
  "Buckwheat",
  "Wild rice",
  "Millet",
];

const extras = [
  "Bowl",
  "Plate",
  "Salad",
  "Stir-fry",
  "Wrap",
  "Skillet",
  "Soup",
  "Power Bowl",
  "Tray Bake",
  "One-Pot",
];

function caloriesFor(mealType, dietStyle, i) {
  let min = 350;
  let max = 650;

  if (mealType === "breakfast") {
    min = 300;
    max = 550;
  } else if (mealType === "small-meal") {
    min = 150;
    max = 300;
  } else if (mealType === "dinner") {
    min = 450;
    max = 750;
  }

  // Adjust by diet style
  if (dietStyle === "keto") {
    min += 50;
    max += 50;
  } else if (dietStyle === "high-protein") {
    min += 30;
    max += 30;
  } else if (dietStyle === "low-fodmap") {
    max -= 20;
  }

  const rand = (Math.sin(i * 12.9898) * 43758.5453) % 1; // deterministic-ish
  const base = min + Math.abs(rand) * (max - min);

  return Math.round(base / 10) * 10; // round to nearest 10
}

function flagsFor(dietStyle, mealType, i) {
  let ibsSafe = dietStyle === "low-fodmap";
  let glutenFree = dietStyle === "keto" || dietStyle === "low-fodmap";
  let immuneSafe = dietStyle === "mediterranean";

  // Sprinkle more safe options based on index
  if (i % 5 === 0) ibsSafe = true;
  if (i % 3 === 0) glutenFree = true;
  if (i % 2 === 0) immuneSafe = true;

  // Small-meals often tend to be "cleaner"
  if (mealType === "small-meal") {
    ibsSafe = ibsSafe || i % 2 === 1;
    glutenFree = true;
  }

  return { ibsSafe, glutenFree, immuneSafe };
}

function buildRecipe(mealType, cuisine, protein, carb, i) {
  // Very rough quantity logic by mealType
  const baseProtein = mealType === "small-meal" ? 60 : mealType === "breakfast" ? 90 : 120;
  const baseCarb = mealType === "small-meal" ? 40 : 70;
  const vegQty = mealType === "small-meal" ? 0.5 : 1;

  const ingredients = [
    {
      name: protein,
      unit: "g",
      quantity: baseProtein,
    },
    {
      name: carb,
      unit: "g",
      quantity: baseCarb,
    },
    {
      name: "Mixed non-starchy vegetables",
      unit: "cup",
      quantity: vegQty,
    },
    {
      name: "Olive oil",
      unit: "tbsp",
      quantity: mealType === "small-meal" ? 0.5 : 1,
    },
    {
      name: `${cuisine} seasoning blend`,
      unit: "tsp",
      quantity: 1,
    },
    {
      name: "Salt",
      unit: "tsp",
      quantity: 0.25,
    },
    {
      name: "Black pepper",
      unit: "tsp",
      quantity: 0.25,
    },
  ];

  const style =
    mealType === "breakfast"
      ? "breakfast bowl"
      : mealType === "small-meal"
      ? "snack plate"
      : "main meal";

  const steps = [
    `Prep the ingredients: dice the ${protein.toLowerCase()}, chop the vegetables, and measure out the grains (${carb.toLowerCase()}).`,
    `Cook the base: prepare the ${carb.toLowerCase()} according to package directions until tender.`,
    `Cook the protein: in a skillet, heat olive oil over medium heat and cook the ${protein.toLowerCase()} with ${cuisine.toLowerCase()} seasoning until fully cooked through.`,
    `Add vegetables: stir the mixed vegetables into the pan and sauté until just tender but still bright in color.`,
    `Assemble the ${style}: add the ${carb.toLowerCase()} to a bowl or plate, top with the cooked ${protein.toLowerCase()} and vegetables, and drizzle with any remaining pan juices.`,
    `Finish & serve: season with salt and pepper to taste and serve warm.`,
  ];

  return { ingredients, steps };
}

function buildMeal(i) {
  const dietStyle = choice(dietStyles, i);
  const mealType = choice(mealTypes, i + 7);
  const cuisine = choice(cuisines, i + 13);
  const protein = choice(proteins, i + 29);
  const carb = choice(carbs, i + 41);
  const extra = choice(extras, i + 61);

  const name = `${cuisine} ${protein} & ${carb} ${extra}`;
  const idBase = `${dietStyle}-${mealType}-${protein}-${carb}-${extra}`
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
  const id = `${idBase}-${i.toString().padStart(4, "0")}`;

  const baseCalories = caloriesFor(mealType, dietStyle, i);
  const flags = flagsFor(dietStyle, mealType, i);
  const recipe = buildRecipe(mealType, cuisine, protein, carb, i);

  // Each meal can often fit multiple diets (e.g. balanced + high-protein)
  const dietStylesForMeal = [dietStyle];
  if (dietStyle === "balanced" && baseCalories >= 450) {
    dietStylesForMeal.push("high-protein");
  }
  if (dietStyle === "mediterranean" && i % 2 === 0) {
    dietStylesForMeal.push("balanced");
  }

  return {
    id,
    name,
    mealType,
    baseCalories,
    dietStyles: Array.from(new Set(dietStylesForMeal)),
    flags,
    recipe,
  };
}

// Build ~1200 meals
const meals = [];
const TOTAL = 1200;

for (let i = 0; i < TOTAL; i++) {
  meals.push(buildMeal(i));
}

const outputPath = path.join(__dirname, "..", "data", "meals.ts");

const fileContents = header + JSON.stringify(meals, null, 2) + ";\n";

fs.mkdirSync(path.join(__dirname, "..", "data"), { recursive: true });
fs.writeFileSync(outputPath, fileContents, "utf8");

console.log(`Generated ${TOTAL} meals into: ${outputPath}`);
